mv ../app/build/outputs/apk/leanbackJavaArm64_v8a/release/*.apk ./
mv ../app/build/outputs/apk/leanbackJavaArmeabi_v7a/release/*.apk ./
mv ../app/build/outputs/apk/leanbackPythonArm64_v8a/release/*.apk ./
mv ../app/build/outputs/apk/leanbackPythonArmeabi_v7a/release/*.apk ./
mv ../app/build/outputs/apk/mobileJavaArm64_v8a/release/*.apk ./
mv ../app/build/outputs/apk/mobileJavaArmeabi_v7a/release/*.apk ./
mv ../app/build/outputs/apk/mobilePythonArm64_v8a/release/*.apk ./
mv ../app/build/outputs/apk/mobilePythonArmeabi_v7a/release/*.apk ./

rm  -rf ../app/build/outputs/apk/leanbackJavaArm64_v8a
rm  -rf ../app/build/outputs/apk/leanbackJavaArmeabi_v7a
rm  -rf ../app/build/outputs/apk/leanbackPythonArm64_v8a
rm  -rf ../app/build/outputs/apk/leanbackPythonArmeabi_v7a
rm  -rf ../app/build/outputs/apk/mobileJavaArm64_v8a
rm  -rf ../app/build/outputs/apk/mobileJavaArmeabi_v7a
rm  -rf ../app/build/outputs/apk/mobilePythonArm64_v8a
rm  -rf ../app/build/outputs/apk/mobilePythonArmeabi_v7a
rm  -rf leanbackJavaArm64_v8a
rm  -rf leanbackJavaArmeabi_v7a
rm  -rf leanbackPythonArm64_v8a
rm  -rf leanbackPythonArmeabi_v7a
rm  -rf mobileJavaArm64_v8a
rm  -rf mobileJavaArmeabi_v7a
rm  -rf mobilePythonArm64_v8a
rm  -rf mobilePythonArmeabi_v7a
